apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-flux-demo

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml

images:
  - name: shivawmm1810/task-manager-app
    newTag: latest