apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository

metadata:
  name: kustomize-flux-gitops
  namespace: flux-system

spec:
  interval: 1m

  url: https://github.com/shivawmm/kustomize-flux-gitops

  ref:
    branch: main